#!/bin/bash
set -e


read -r -p "Site URL: " site_url
read -r -p "Site Full Path: " site_path

[ -f $site_path -o -d $site_path ] || ( echo "No such file or folder found at $site_path"; exit 1 )

echo "Copying template virtual host to apache2"
sudo cp Template/virtual-host.template /etc/apache2/sites-available/$site_url.conf

echo "Modfying variables in the template"
sudo sed -i -e "s/{SITE_URL}/$site_url/g" /etc/apache2/sites-available/$site_url.conf
sudo sed -i -e "s~{SITE_FULL_PATH}~$site_path~g" /etc/apache2/sites-available/$site_url.conf

echo "Adding entry to hosts file for this site"
sudo sh -c "echo '127.0.0.1 $site_url' >> /etc/hosts"

echo "Enabling site with a2ensite"
sudo a2ensite "$site_url.conf" > /dev/null 2>&1

echo "Reloading apache2 settings to acknowledge the new changes"
sudo service apache2 reload
